#!/bin/bash
port=8080
host=0.0.0.0
proxy=""
root=$(git rev-parse --show-toplevel)/angular

if [[ ! ${root:-} ]]; then
    root=../
fi

echo ${root}/node_modules/@angular/cli/bin/ng ${@}
for arg in ${@}; do
    case ${arg} in
        --edit=*) edit=${arg#--edit=};;
        --port=*) port=${arg#--port=};;
        --proxy=*) proxy="--proxy=${arg#--proxy=}";;
        --host=*) host=${arg#--host=};;
        --ssl)
            echo Defining ssl
            ssl=1
            ;;
        --*|*)
            echo ngcompile [ --port=p# --host=h ]
            exit 1;
    esac
done
if [[ ${ssl:-} ]]; then
    ssl="--ssl 1 --ssl-cert /etc/certs/${host}/server.crt --ssl-key /etc/certs/${host}/server.key"
fi

# if [[ ${edit:-} ]]; then
#     sed -e "s,example-com,${edit//./-},g" \
#         -e "s,example.com,${edit},g" \
#         < ${root}/src/app/config.example.ts \
#         > ${root}/src/app/config.ts
# fi

echo "ng (angular2) compile using root ${root} ${ssl}"
echo "${root}/node_modules/@angular/cli/bin/ng serve --verbose --host=${host} --port=${port} ${proxy} ${ssl} 2>&1"

${root}/node_modules/@angular/cli/bin/ng serve --verbose --host=${host} --port=${port} ${proxy} ${ssl} 2>&1 |\
stdbuf -i0 -o0 -e0 grep -Ev '(building modules|\[emitted\])' |\
stdbuf -i0 -o0 -e0 uncolor | \
stdbuf -i0 -o0 -e0 tee ${root}/log 2>&1 | \
stdbuf -i0 -o0 -e0 sed -r -e 's,^ERROR in /,/,g' -e 's@([a-z0-9A-Z/]+)[[:space:]]+\(([0-9]+),([0-9]+)\):(.*)@\1:\2:\3:\4@g'
# sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
# sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
# echo ... | sed -r "s/./\x1B/g"
